version: '3'

services:
  gobarber-api:
    build: .
    container_name: GoBarberAPI
    ports:
      - '3333:3333'
      - '9229:9229'
    networks:
      - gobarber-network
    depends_on:
      - gobarber-redis
      - gobarber-postgres
      - gobarber-mongo
      - gobarber-migrate
    command: yarn dev

  gobarber-queue:
    build: .
    container_name: GoBarberQueue
    networks:
      - gobarber-network
    depends_on:
      - gobarber-redis
      - gobarber-postgres
      - gobarber-mongo
      - gobarber-migrate
    command: yarn queue

  gobarber-migrate:
    build: .
    container_name: GoBarberMigrate
    networks:
      - gobarber-network
    depends_on:
      - gobarber-postgres
    command: yarn sequelize db:migrate

  gobarber-redis:
    image: redis:alpine
    container_name: GoBarberRedis
    volumes:
      - redis:/data
    networks:
      - gobarber-network

  gobarber-postgres:
    image: postgres
    container_name: GoBarberPostgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - gobarber-network

  gobarber-mongo:
    image: mongo
    container_name: GoBarberMongo
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb
    networks:
      - gobarber-network

volumes:
  postgresql:
  redis:
  mongo:

networks:
  gobarber-network:
    driver: bridge
